---
alias: rubydistros

slack:
  notify_channel:
    - chef-infra-notify

pipelines:
  - docker/build
  - build-windows:
      definition: .expeditor/build-windows-docker.yml

subscriptions:
  - workload: pull_request_merged:{{github_repo}}:{{release_branch}}:*
    actions:
    - trigger_pipeline:docker/build

    